[package]
name = "pawonee-backend-service"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[dependencies]
axum = { version = "=0.8.1", features = ["json"] }
tokio = { version = "=1.42.0", features = ["full"] }
sqlx = { version = "=0.8.2", features = ["postgres", "runtime-tokio", "migrate"] }
serde = { version = "=1.0.215", features = ["derive"] }
serde_json = { version = "=1.0.133" }
tower-http = { version = "0.6.1", features = ["cors"] }

[dev-dependencies]
axum-test = "16.0.0"
